---
title: " "
author: "Tao Huang"
date:  "`r Sys.Date()`"
output: html_document
---

#load the packages
```{r}
#install.packages("tidyverse")
library("tidyverse")
# install.packages("dataRetrieval")
library(dataRetrieval)
# install.packages("zoo") 
library(zoo)
library(raster)
library("maptools")
library(baseflow)
#library("EcoHydRology")
library("foreign")
# install.packages("moments") 
library("moments")
library("EnvStats")
library("rnoaa")
# install.packages("gradDescent") 
library("gradDescent")
#install.packages("pracma"
library("pracma")
#install.packages("nls2")
library("nls2")
```

```{r}
# read data
usgs<-read.csv("wt_ID.csv")
#usgs<-read.dbf("wt_ID.dbf") #DRAIN_SQKM

usgs<-usgs[usgs$site_no<1e+08,]
usgs$site_no<-as.character(usgs$site_no)

meanAugT_df<-data.frame(agency_cd= " ",site_no="", Date=as.Date("2000-01-01",format="%Y-%m-%d"),X_00010_00003=0,    X_00010_00003_cd= "",X_00060_00003=0,    X_00060_00003_cd= "",yr="",mo=0 , ele=0)

#for (id in usgs) {
 for (id in usgs$site_no ) {
  siteNumber <- as.character(id) 
  parameterCd <- c("00010","00060") #00060: Discharge, cubic feet per second
 ChoptankInfo <- readNWISsite(siteNumber)
 #ChoptankInfo$alt_va : Gage datum feet above NGVD29
  statCd <- c("00003") # 00003	MEAN
  startDate <- "2014-06-01"
endDate <- "2021-09-01"
meanT <-   readNWISdv(siteNumber, parameterCd, 
                                 startDate, endDate, statCd=statCd)
  if (dim(meanT )[2]>5){
meanT$yr<- format(meanT$Date, format = "%Y") 
meanT$mo<-as.numeric(format(meanT$Date, format = "%m"))
meanAugT<-meanT[meanT$mo==8,c("agency_cd","site_no","Date","X_00010_00003","X_00010_00003_cd","X_00060_00003","X_00060_00003_cd","yr","mo"  )]
meanAugT$ele<-ChoptankInfo$alt_va
meanAugT_df <-rbind(meanAugT_df,meanAugT)
print(Sys.time())
}
}

# clean the data
meanAugT_df<-meanAugT_df[-1,]
meanAugT_df<-meanAugT_df[!meanAugT_df$site_no=="13185000" ,]

save(meanAugT_df,file="meanQT_14_21.Rdata")

```

```{r}
load("meanQT_14_21.Rdata")
```

```{r}
setwd("C:/Users/taohuang/Documents/Tao/Data/PRISM")
temp_all<-data.frame(STAID<-c("00"),yr<-c(0),RASTERVALU<-0)
colnames(temp_all)<-c("STAID","yr","RASTERVALU")
for (yr in c(2014:2020)) {
  temp<-read.dbf(paste("temp",yr,".dbf",sep=""))
  temp$yr<-yr
    temp<-temp[,c("STAID","yr","RASTERVALU")]
    temp_all<-rbind(temp_all,temp)
}
temp_all<-temp_all[-1,]
head(temp_all)
```

```{r}
meanAugT_all<-merge(meanAugT_df,temp_all,by.x=c("site_no","yr"),by.y=c("STAID","yr"))
meanAugT_all<-meanAugT_all[!is.na(meanAugT_all$X_00010_00003),]
summary(meanAugT_all)
head(meanAugT_all)
```

```{r}
save(meanAugT_all,file="meanAugT_all.Rdata")
```

#monthly air temp
```{r}
colnames(meanAugT_all)<-c(colnames(meanAugT_all)[1:4],"Daily_Stream_T","X_00010_00003_cd", "Daily_Q", "X_00060_00003_cd" ,"mo"  ,             "ele"         ,     "Monthly_air_T"  )

meanAugT_all_mo<-meanAugT_all %>%
  group_by(site_no  ,yr) %>%
  summarise(monthly_stream_T = mean(Daily_Stream_T), monthly_stream_Q = mean(Daily_Q),ele= mean(ele), monthly_air_T=mean(Monthly_air_T) )

head(meanAugT_all_mo)
```

```{r}
g<-read.dbf("C:/Users/taohuang/Documents/Tao/Data/gagesII_9322_point_shapefile/gagesII_9322_sept30_2011.dbf")
g$STAID<-as.character(g$STAID)
meanAugT_all_mo2<-merge(g,meanAugT_all_mo,by.x="STAID",by.y="site_no")
meanAugT_all_mo2
meanAugT_all_mo3<-meanAugT_all_mo2[meanAugT_all_mo2$CLASS=="Ref",]
dim(meanAugT_all_mo3)
```


```{r}
plot(meanAugT_all_mo$monthly_air_T, meanAugT_all_mo$monthly_stream_T)
plot(meanAugT_all_mo3$monthly_air_T,meanAugT_all_mo3$monthly_stream_T)
```


```{r}
summary(lm(meanAugT_all_mo$monthly_stream_T~ meanAugT_all_mo$monthly_stream_Q +meanAugT_all_mo$monthly_air_T+ meanAugT_all_mo$ele))

summary(lm(meanAugT_all_mo3$monthly_stream_T~ meanAugT_all_mo3$monthly_stream_Q +meanAugT_all_mo3$monthly_air_T+ meanAugT_all_mo3$ele))
```


```{r}

  

plot(meanAugT_all$Daily_Q  ,meanAugT_all$Daily_Stream_T )

plot(meanAugT_all$Monthly_air_T  ,meanAugT_all$Daily_Stream_T )

plot(meanAugT_all$ele  ,meanAugT_all$Daily_Stream_T )

```


```{r}
summary(lm(meanAugT_all$Daily_Stream_T~meanAugT_all$Monthly_air_T+ meanAugT_all$Daily_Q+meanAugT_all$ele ))
```

```{r}
summary(lm(meanAugT_all$X_00010_00003~meanAugT_all$RASTERVALU+meanAugT_all$X_00060_00003))
summary(lm(meanAugT_all$X_00010_00003~meanAugT_all$RASTERVALU+ log(meanAugT_all$X_00060_00003)))

```




#Read data
```{r}
i<-read.csv("icevelocity.txt",sep = "",header = F)
i
v<-i$V2
z<-i$V1
```

# Q7
```{r}
rho=1
g=9.8
A=seq(1e-18,10e-18,  0.1e-18)
n=seq(1, 4, 0.01)
```

```{r}
result<-data.frame(A=0,n=0,RMSE=0)

for (q in c(1:length(A)))
{
  for (m in c(1:length(n)))
  {
    At=A[q]
    nt=n[m]
    Vm= v[1]-At*(rho*g*sin(10*pi/180) )^nt*z^(nt+1)
    #RMSE(q,m)= sqrt(mean((Vm(:,n)-v).^2));
    RMSE<-sqrt(mean((Vm-v)^2))
    
    result_A_n<-data.frame(A=At,n=nt,RMSE=RMSE)
    result<-rbind(result,result_A_n)
  }
}
   result<-result[-1,] 
save(result,file="result.Rdata")
```

```{r}
result[result$RMSE==min(result$RMSE),]
#plot(result$A,result$RMSE)
```

#Q8
```{r}
plot(result$A,result$RMSE,xlab="A",ylab="RMSE")
plot(result$n,result$RMSE,xlab="n",ylab="RMSE")
```

# Q9
```{r}
#rmse <- function(A, n) sqrt(mean(( v[1]-A*(rho*g*sin(10*pi/180) )^n*z^(n+1)  -v)^2))

rmse <- function(p) sqrt(mean(( v[1]-p[1]*(rho*g*sin(10*pi/180) )^p[2]*z^(p[2]+1)  -v)^2))

fminsearch( rmse,  c(10e-18 ,4) , method="Nelder-Mead")

# Vm= v[1]-At*(rho*g*sin(10*pi/180) )^nt*z^(nt+1)
```

# Q10
```{r}

A_RMSE<-data.frame(A=0,RMSE=0)

for (t in c(1:1000))
{
  rand_i[[t]] <- i[sample(nrow(i), size=  round(dim(i)[1]*0.9)), ]
z<-  rand_i[[t]][,1]
v<-  rand_i[[t]][,2]

rmse <- function(p) sqrt(mean(( 80.08673	-p[1]*(rho*g*sin(10*pi/180) )^p[2]*z^(p[2]+1)  -v)^2))


f_result<-fminsearch( rmse,  c(10e-18 ,4) , method="Nelder-Mead")


f_result_A_RMSE <-data.frame(A=f_result$xmin[1],RMSE=f_result$fmin)

A_RMSE<-rbind(A_RMSE, f_result_A_RMSE)


}

A_RMSE<-A_RMSE[-1,]

save( A_RMSE,file="A_RMSE.Rdata")

```

```{r}
hist(A_RMSE$A,main="Histogram of A")
hist(A_RMSE$RMSE,main="Histogram of RMSE")
```

