---
title: "climate data online"
author: "Tao Huang"
date: "`r Sys.Date()`"
output: html_document
---

In streams, Rainbow Trout prefer water temperatures similar to those favored by Brown Trout, from 54°F to 66°F, while lake-dwellers select waters between 45°F and 64°F. The maximum tolerable water temperature is 77°F, but some populations may be able to withstand temperatures in the low eighties for short periods of time.

```{r  , warning=FALSE, echo=FALSE, include=FALSE }
#install.packages("tidyverse")
library("tidyverse")
# install.packages("dataRetrieval")
library(dataRetrieval)
# install.packages("zoo") 
library(zoo)
library(raster)
library("maptools")
library(baseflow)
library("EcoHydRology")
```

```{r}
siteNumber <- "13296000" 
ChoptankInfo <- readNWISsite(siteNumber)
#ChoptankInfo
parameterCd <- "00060"
ChoptankInfo
```

```{r}
allQ <- readNWISdv(siteNumber,parameterCd,"2012-10-01","2021-09-03")
allQ$yr<- format(allQ$Date, format = "%Y") 
allQ$mo<-as.numeric(format(allQ$Date, format = "%m"))
summerQ<-allQ[allQ$mo %in% c(6,7,8),]
head(summerQ)
```

```{r}
ggplot(data=summerQ,aes(x=yr, y=X_00060_00003   ))+geom_boxplot()+ scale_y_log10()
```

```{r}
ChoptankInfo <- readNWISsite(siteNumber)
#ChoptankInfo
parameterCd <- "00010"
ChoptankInfo

```

#https://idfg.idaho.gov/ifwis/fishingPlanner/water/1147337442696

```{r}
allT <- readNWISdv(siteNumber,parameterCd,"2012-10-01","2021-09-03")
allT$yr<- format(allT$Date, format = "%Y") 
allT$mo<-as.numeric(format(allT$Date, format = "%m"))
summerT<-allT[allT$mo %in% c(6,7,8),]
head(summerT)

#summerT$abv66<-0
#summerT[summerT$X_00010_00003 > (66-32)*5/9 ,]$abv66<-1
#abv66<-aggregate(summerT[,c("X_00010_00003","yr")],list=c("X_00010_00003"),FUN=mean())
```

```{r}
ggplot(data=summerT,aes(x=yr, y=X_00010_00003   ))+ geom_boxplot()+ggtitle(ChoptankInfo$station_nm) + ylab("Stream temperature (degrees Celsius)") + xlab("Year")

summerT$yr<- as.integer(summerT$yr) 
ggplot(data=summerT,aes(x=Date, y=X_00010_00003   ))+geom_point()+stat_smooth()+ggtitle(ChoptankInfo$station_nm)+ ylab("Stream temperature (degrees Celsius)") + xlab("Year")

ggplot(data=summerT,aes(x=Date, y=X_00010_00003   ))+geom_point()+stat_smooth()+ggtitle(ChoptankInfo$station_nm)+ ylab("Stream temperature (degrees Celsius)") + xlab("Year")+geom_hline(yintercept = (66-32)*5/9)

```





```{r}
allQ <- readNWISdv(siteNumber,parameterCd,"1994-09-01","2021-09-06")

allQ$yr<-format(allQ$Date, format = "%Y")
allQ$wyr<-0
#allQ[allQ$Date>= as.Date("2003-10-01") & allQ$Date<as.Date("2004-10-01"),]$wyr<-2004
#allQ[allQ$Date>= as.Date("2004-10-01") & allQ$Date<as.Date("2005-10-01"),]$wyr<-2005
allQ[allQ$Date>= as.Date("2005-10-01") & allQ$Date<as.Date("2006-10-01"),]$wyr<-2006
allQ[allQ$Date>= as.Date("2006-10-01") & allQ$Date<as.Date("2007-10-01"),]$wyr<-2007
allQ[allQ$Date>= as.Date("2007-10-01") & allQ$Date<as.Date("2008-10-01"),]$wyr<-2008
allQ[allQ$Date>= as.Date("2008-10-01") & allQ$Date<as.Date("2009-10-01"),]$wyr<-2009
allQ[allQ$Date>= as.Date("2009-10-01") & allQ$Date<as.Date("2010-10-01"),]$wyr<-2010
allQ[allQ$Date>= as.Date("2010-10-01") & allQ$Date<as.Date("2011-10-01"),]$wyr<-2011
allQ[allQ$Date>= as.Date("2011-10-01") & allQ$Date<as.Date("2012-10-01"),]$wyr<-2012
allQ[allQ$Date>= as.Date("2012-10-01") & allQ$Date<as.Date("2013-10-01"),]$wyr<-2013
allQ[allQ$Date>= as.Date("2013-10-01") & allQ$Date<as.Date("2014-10-01"),]$wyr<-2014
allQ[allQ$Date>= as.Date("2014-10-01") & allQ$Date<as.Date("2015-10-01"),]$wyr<-2015
allQ[allQ$Date>= as.Date("2015-10-01") & allQ$Date<as.Date("2016-10-01"),]$wyr<-2016
allQ[allQ$Date>= as.Date("2016-10-01") & allQ$Date<as.Date("2017-10-01"),]$wyr<-2017
allQ[allQ$Date>= as.Date("2017-10-01") & allQ$Date<as.Date("2018-10-01"),]$wyr<-2018
allQ[allQ$Date>= as.Date("2018-10-01") & allQ$Date<as.Date("2019-10-01"),]$wyr<-2019
allQ[allQ$Date>= as.Date("2019-10-01") & allQ$Date<as.Date("2020-10-01"),]$wyr<-2020

summer_2020<-allQ[allQ$Date>= as.Date("2020-06-01") & allQ$Date<as.Date("2020-08-31"),]
summer_2021<-allQ[allQ$Date>= as.Date("2021-06-01") & allQ$Date<as.Date("2021-08-31"),]

allQ

allQ$wyr<-as.factor(allQ$wyr)
ggplot(data=allQ,aes(x=wyr, y=X_00060_00003   ))+geom_boxplot()
allQ$wyr<-as.numeric(as.character(allQ$wyr))
head(allQ)
save(allQ,file = "13092747.Rdata")

```

```{r}
summer_2015<-allQ[allQ$Date>= as.Date("2015-06-01") & allQ$Date<as.Date("2015-08-31"),]
hist(summer_2015$X_00060_00003, xlim=c(0,700), ylim=c(0,50))
summer_2016<-allQ[allQ$Date>= as.Date("2016-06-01") & allQ$Date<as.Date("2016-08-31"),]
hist(summer_2016$X_00060_00003, xlim=c(0,700), ylim=c(0,50))
summer_2017<-allQ[allQ$Date>= as.Date("2017-06-01") & allQ$Date<as.Date("2017-08-31"),]
hist(summer_2017$X_00060_00003, xlim=c(0,700), ylim=c(0,50))
summer_2018<-allQ[allQ$Date>= as.Date("2018-06-01") & allQ$Date<as.Date("2018-08-31"),]
hist(summer_2018$X_00060_00003, xlim=c(0,700), ylim=c(0,50))
summer_2019<-allQ[allQ$Date>= as.Date("2019-06-01") & allQ$Date<as.Date("2019-08-31"),]
hist(summer_2019$X_00060_00003, xlim=c(0,700) , ylim=c(0,50) )
summer_2020<-allQ[allQ$Date>= as.Date("2020-06-01") & allQ$Date<as.Date("2020-08-31"),]
hist(summer_2020$X_00060_00003, xlim=c(0,700) , ylim=c(0,50) )

summer_1617<-rbind(summer_2016,summer_2017)
summer_1517<-rbind(summer_2015,summer_1617)
summer_1518<-rbind(summer_2018,summer_1617)
hist(summer_1518$X_00060_00003, xlim=c(0,700) , ylim=c(0,200) )

summer_2021<-allQ[allQ$Date>= as.Date("2021-06-01") & allQ$Date<as.Date("2021-08-31"),]
hist(summer_2021$X_00060_00003, xlim=c(0,700) , ylim=c(0,50) )
par(new=T)


```


<!-- ```{r} -->
<!-- load("14092750.Rdata") -->
<!-- ``` -->

```{r}
hydrograph(allQ[allQ$wyr %in% c(2010:2014),c(3:4)])
```




<!-- ```{r} -->


<!-- hist(c[c$wy=="2015",]$PRCP,breaks = c(0,5,10,15,25,30) ) -->
<!-- hist(c[c$wy=="2016",]$PRCP ) -->
<!-- hist(c[c$wy=="2017",]$PRCP ) -->
<!-- hist(c[c$wy=="2018",]$PRCP ,breaks = c(0,5,10,15,25,30)) -->
<!-- hist(c[c$wy=="2019",]$PRCP ) -->

<!-- plot(c[c$wy=="2015",]$DATE,c[c$wy=="2015",]$PRCP ) -->
<!-- plot(c[c$wy=="2016",]$DATE,c[c$wy=="2016",]$PRCP) -->
<!-- plot(c[c$wy=="2018",]$DATE,c[c$wy=="2018",]$PRCP) -->
<!-- plot(c[c$wy=="2019",]$DATE,c[c$wy=="2019",]$PRCP) -->

<!-- hist(allQ[allQ$wyr=="2015" ,]$X_00060_00003,breaks = c(0,5000,10000,15000,25000,30000)) -->
<!-- hist(allQ[allQ$wyr=="2016" ,]$X_00060_00003) -->
<!-- hist(allQ[allQ$wyr=="2017" ,]$X_00060_00003) -->
<!-- hist(allQ[allQ$wyr=="2018" ,]$X_00060_00003,breaks = c(0,5000,10000,15000,25000,30000)) -->
<!-- ``` -->


<!-- ```{r} -->

<!-- meanQ<-aggregate(allQ$X_00060_00003 ,list(allQ$wyr ),mean) #cubic feet per second (Mean) -->



<!-- colnames(meanQ)<-c("wyr","Q") -->

<!-- rq<- merge(meanQ,mean_rain,by.x="wyr",by.y="wyr") -->
<!-- rq$rp<-rq$Q *(0.3048)^3*86400* 365/ (271 *1.609*1.609*10^6)/ (rq$mean_rain*12*10/1000)  -->
<!-- # ft^3/s*s/d*d/(mi^2* m/mi *m/mi) -->
<!-- rq -->




<!-- ``` -->


<!-- ```{r} -->
<!-- for (m in c(8:9)) { -->
<!--  print(paste("asc",m,"<-paste(",sep="")) -->
<!--   print(paste("PRISM_ppt_stable_4kmM3_,wyr,0",m,"_asc.asc",",sep=",sep="")) -->

<!--    print(paste("r",m,sep="")) -->

<!-- } -->
<!-- ``` -->



```{r}
df<-data.frame("wyr"=0,"prcp"=0)

for (wyr in c(2006:2019))
{
  setwd(paste("C:/Users/taohuang/Documents/Tao/Data/PRISM/PRISM_ppt_stable_4kmM3_",wyr-1,"_all_asc",sep=""))
  print(wyr)
  asc10<-paste("PRISM_ppt_stable_4kmM3_",wyr-1,"10_asc.asc",sep="")
  r10<-raster(asc10)
    asc11<-paste("PRISM_ppt_stable_4kmM3_",wyr-1,"11_asc.asc",sep="")
  r11<-raster(asc11)
    asc12<-paste("PRISM_ppt_stable_4kmM3_",wyr-1,"12_asc.asc",sep="")
  r12<-raster(asc12)
    setwd(paste("C:/Users/taohuang/Documents/Tao/Data/PRISM/PRISM_ppt_stable_4kmM3_",wyr,"_all_asc",sep=""))
      asc1<-paste("PRISM_ppt_stable_4kmM3_",wyr,"01_asc.asc",sep="")
  r1<-raster(asc1)
        asc2<-paste("PRISM_ppt_stable_4kmM3_",wyr,"02_asc.asc",sep="")
  r2<-raster(asc2)
asc3<-paste("PRISM_ppt_stable_4kmM3_",wyr,"03_asc.asc",sep="")
  r3<-raster(asc3)
asc4<-paste("PRISM_ppt_stable_4kmM3_",wyr,"04_asc.asc",sep="")
              r4<-raster(asc4)
asc5<-paste("PRISM_ppt_stable_4kmM3_",wyr,"05_asc.asc",sep="")
              r5<-raster(asc5)
asc6<-paste("PRISM_ppt_stable_4kmM3_",wyr,"06_asc.asc",sep="")
              r6<-raster(asc6)
asc7<-paste("PRISM_ppt_stable_4kmM3_",wyr,"07_asc.asc",sep="")
              r7<-raster(asc7)
asc8<-paste("PRISM_ppt_stable_4kmM3_",wyr,"08_asc.asc",sep="")
              r8<-raster(asc8)
asc9<-paste("PRISM_ppt_stable_4kmM3_",wyr,"09_asc.asc",sep="")
              r9<-raster(asc9)
             r<-r1+r2+r3+r4+r5+r6+r7+r8+r9+r10+r11+r12 
             class(r)
             
             poly <- readShapePoly("C:/Users/taohuang/Documents/Tao/Data/14400000/layers/globalwatershed.shp")
             ex <- extract(r, poly, fun=mean, na.rm=TRUE, df=TRUE)
             
             df_wyr<-data.frame("wyr"=wyr,"prcp"=ex$layer)
              df<-rbind( df_wyr, df)
}
#save(df,file="C:/Users/taohuang/Documents/Tao/NWCC/NWCC/14092750_rain.Rdata")

```

```{r}
load("14092750_rain.Rdata")
```


```{r}

meanQ<-aggregate(allQ$X_00060_00003 ,list(allQ$wyr ),mean) #cubic feet per second (Mean)

colnames(meanQ)<-c("wyr","Q")

rq<- merge(meanQ, df,by.x="wyr",by.y="wyr")
rq$rp<-rq$Q *(0.3048)^3*86400* 365/ (ChoptankInfo$drain_area_va *1.609*1.609*10^6)/ (rq$prcp /1000) 
# ft^3/s*s/d*d/(mi^2* m/mi *m/mi)
rq

plot(rq$prcp,rq$Q)
plot(rq$prcp,rq$rp)

plot(rq[rq$wyr %in% c(2010:2014),]$prcp,rq[rq$wyr %in% c(2010:2014),]$Q)
plot(rq[rq$wyr %in% c(2010:2014),]$prcp,rq[rq$wyr %in% c(2010:2014),]$rp)

plot(rq[rq$wyr %in% c(2006:2011),]$prcp,rq[rq$wyr %in% c(2006:2011),]$rp)
plot(rq[rq$wyr %in% c(2013:2018),]$prcp,rq[rq$wyr %in% c(2013:2018),]$rp)
```

