---
title: " random forest"
author: "Tao Huang"
date: "`r Sys.Date()`"
output: html_document
---

# load packages
```{r  , warning=FALSE, echo=FALSE, include=FALSE }
#install.packages("tidyverse")
library("tidyverse")
# install.packages("dataRetrieval")
library(dataRetrieval)
# install.packages("zoo") 
library(zoo)
library(raster)
library("maptools")
library(baseflow)
#library("EcoHydRology")
library("foreign")
# install.packages("moments") 
library("moments")
library("EnvStats")
library("rnoaa")
```

# MAX 00001	MAXIMUM
```{r}
# read data
usgs<-read.csv("wt_ID.csv") #DRAIN_SQKM

meanAugT_df<-data.frame(agency_cd= " ",site_no="", Date=as.Date("2000-01-01",format="%Y-%m-%d"),X_00010_00001=0,X_00010_00003=0,    X_00010_00003_cd= "",X_00060_00003=0,    X_00060_00003_cd= "",yr="",mo=0,ele=0 )

usgs$site_no2<-usgs$site_no
#usgs[ (usgs$site_no<10000000),]$site_no2<-paste("0",usgs[ (usgs$site_no<10000000),]$site_no,sep="")
usgs<-usgs[usgs$site_no<1e+08,]
 usgs$site_no2<-as.character(usgs$site_no2)
 
#for (id in usgs) {
 for (id in usgs$site_no2 ) {
  siteNumber <- as.character(id) 
  parameterCd <- c("00010","00060") #00060: Discharge, cubic feet per second
 ChoptankInfo <- readNWISsite(siteNumber)
 #ChoptankInfo$alt_va : Gage datum feet above NGVD29
  statCd <- c("00001","00003")  
  startDate <- "1993-06-01"
endDate <- "2021-09-01"
meanT <-   readNWISdv(siteNumber, parameterCd, 
                                 startDate, endDate, statCd=statCd)
  if (dim(meanT )[2]>7){
meanT$yr<- format(meanT$Date, format = "%Y") 
meanT$mo<-as.numeric(format(meanT$Date, format = "%m"))
meanAugT<-meanT[meanT$mo==8,c("agency_cd","site_no","Date","X_00010_00001","X_00010_00003","X_00010_00003_cd","X_00060_00003","X_00060_00003_cd","yr","mo"  )]
meanAugT$ele<-ChoptankInfo$alt_va
meanAugT$lat<-dec_lat_va
  
meanAugT$long<- dec_long_va

meanAugT_df <-rbind(meanAugT_df,meanAugT)
}
}

# clean the data
meanAugT_df<-meanAugT_df[-1,]
meanAugT_df<-meanAugT_df[!meanAugT_df$site_no=="13185000" ,]

save(meanAugT_df,file="maxQT_93_21_ID.Rdata")

```

```{r}
load("maxQT_93_21_ID.Rdata") #daily
head(meanAugT_df)
```

#meanT for each site
```{r}

meanAugT_df_mean<-
meanAugT_df %>%
  group_by(site_no) %>%
  summarize(mean_T=mean(X_00010_00003, na.rm = TRUE))

write.csv(meanAugT_df_mean, file="meanAugT_df_mean.csv")

  
```


#weather data
```{r}
#To get a full and current list of stations
stations <- ghcnd_stations()
#save(stations,file="stations.Rdata")
```


```{r}
summary(complete.cases(meanAugT_df[,c("site_no","Date","X_00010_00001","X_00060_00003","yr","mo","ele" )]))
meanAugT_df2<-meanAugT_df[complete.cases(meanAugT_df[,c("site_no","Date","X_00010_00001","X_00010_00003","X_00060_00003","yr","mo","ele" )]),]
#meanAugT_df2<-meanAugT_df2[!meanAugT_df2$site_no=="06190540",]
 

summary(lm(meanAugT_df2$X_00010_00003~meanAugT_df2$X_00060_00003+meanAugT_df2$ele))
summary(lm(meanAugT_df2$X_00010_00001~meanAugT_df2$X_00060_00003+meanAugT_df2$ele))
```











```{r}
# read data
usgs<-read.dbf("usgs_wt_ID_nearest.dbf") #DRAIN_SQKM

meanAugT_df<-data.frame(agency_cd= " ",site_no="", Date=as.Date("2000-01-01",format="%Y-%m-%d"),X_00010_00003=0,    X_00010_00003_cd= "",X_00060_00003=0,    X_00060_00003_cd= "",yr="",mo=0 )

#for (id in usgs) {
 for (id in usgs$STAID) {
  siteNumber <- as.character(id) 
  parameterCd <- c("00010","00060") #00060: Discharge, cubic feet per second
 ChoptankInfo <- readNWISsite(siteNumber)
 #ChoptankInfo$alt_va : Gage datum feet above NGVD29
  statCd <- c("00003") # 00003	MEAN
  startDate <- "2012-06-01"
endDate <- "2021-09-01"
meanT <-   readNWISdv(siteNumber, parameterCd, 
                                 startDate, endDate, statCd=statCd)
  if (dim(meanT )[2]>7){
meanT$yr<- format(meanT$Date, format = "%Y") 
meanT$mo<-as.numeric(format(meanT$Date, format = "%m"))
meanAugT<-meanT[meanT$mo==8,c("agency_cd","site_no","Date","X_00010_00003","X_00010_00003_cd","X_00060_00003","X_00060_00003_cd","yr","mo"  )]
meanAugT_df <-rbind(meanAugT_df,meanAugT)
}
}

# clean the data
meanAugT_df<-meanAugT_df[-1,]
meanAugT_df<-meanAugT_df[!meanAugT_df$site_no=="13185000" ,]
meanAugT_df$ele<-ChoptankInfo$alt_va

save(meanAugT_df,file="meanQT_12_21.Rdata")

```

```{r}
load("meanQT_12_21.Rdata")
```


```{r}
summary(meanAugT_df)
summary(complete.cases(meanAugT_df[,c("site_no","Date","X_00010_00003","X_00060_00003","yr","mo","ele" )]))
```










```{r}
#load("C:/Users/taohuang/Downloads/Chapter_2-main/meanAugQT_df.Rdata")
meanAugT_df<-merge(meanAugT_df,usgs,by.x="site_no",by.y="STAID")
meanAugT_df<-meanAugT_df[!is.na(meanAugT_df$X_00010_00003),]
plot(meanAugT_df$X_00060_00003,meanAugT_df$X_00010_00003)
plot(meanAugT_df$DRAIN_SQKM ,meanAugT_df$X_00010_00003)

```

```{r}
meanAugT_df<-meanAugT_df[meanAugT_df$DRAIN_SQKM<max(meanAugT_df$DRAIN_SQKM),]
summary(lm(meanAugT_df$X_00010_00003~meanAugT_df$X_00060_00003+meanAugT_df$DRAIN_SQKM))
```


```{r}
 for (id in  meanAugT_df$site_no) {
   
   if(  length(meanAugT_df[meanAugT_df$site_no==id,]$X_00010_00003) >= (2021-2012+1)*31*0.9 ){
     p<-  qplot( meanAugT_df[meanAugT_df$site_no==id,]$X_00010_00003,
      geom="histogram",
      binwidth = 1,  
      main =  paste(id, "skewness=", skewness( meanAugT_df[meanAugT_df$site_no==id,]$X_00010_00003), ", Coefficient of Variation=", cv(meanAugT_df[meanAugT_df$site_no==id,]$X_00010_00003))         , 
      xlab = "Stream T",  
      fill=I("blue")
#,      col=I("red"), 
#      alpha=I(.2),
#      xlim=c(20,50)
)
     
     
     
     png(paste(id,".png",sep=""))

  print(p)

   
     dev.off()
     
 #    hist(meanAugT_df[meanAugT_df$site_no==id,]$X_00010_00003, main=id,       xlab = "Stream T")
   }
   
#  hist(meanAugT_df[meanAugT_df$site_no==id,]$X_00010_00003)
   
   
   
 }

```


```{r}

#mean of each site
meanAugT_df_mean<-
meanAugT_df %>%
  group_by(site_no) %>%
  summarize(mean_T=mean(X_00010_00003, na.rm = TRUE))

meanAugT_df_usgs<-merge(meanAugT_df_mean,usgs,by="site_no")

```

```{r}
# wrong data
meanAugT_df_usgs<-meanAugT_df_usgs[!meanAugT_df_usgs$site_no=="13185000",] 

cor<-cor.test(meanAugT_df_usgs$S1_93_11,meanAugT_df_usgs$mean_T)

new_old_t<-meanAugT_df_usgs[,c("S1_93_11","mean_T")]

t.test(new_old_t$S1_93_11,new_old_t$mean_T)

old_t<-meanAugT_df_usgs[,c("site_no","S1_93_11" )]
old_t$model<-"NorWeST"
colnames(old_t)<-c("site_no","t","model" )

new_t<-meanAugT_df_usgs[,c("site_no","mean_T" )]
new_t$model<-"USGS (2012-2021)"
colnames(new_t)<-c("site_no","t","model" )

models<-rbind(old_t,new_t)



ggplot(models, aes( model, t))+ geom_boxplot()+ 
  ylab("Stream T")+
  xlab(" ") 

#plot(meanAugT_df_usgs$S1_93_11, meanAugT_df_usgs$mean_T)

all_t<-c(meanAugT_df_usgs$S1_93_11,meanAugT_df_usgs$mean_T)

all_t %>% max() %>% ceiling()

l<-seq( all_t %>% min() %>% floor(), all_t %>% max() %>% ceiling() , by = 1)
ldf<-data.frame(x=l,y=l)

ggplot() +
  geom_point(data=meanAugT_df_usgs, aes(x=S1_93_11, y=mean_T))+
  geom_line( data=ldf , aes(x=x, y=y))+
  xlab("NorWeST") + 
  ylab("USGS (2012-2021)") +
  ggtitle(  paste(      "Mean August Temperature, correlation coefficient=", cor$estimate ))

```




```{r}
ggplot(data=meanAugT,aes(x=yr, y=X_00010_00003   ))+ geom_boxplot()+ggtitle(" ") + ylab("Stream temperature (degrees Celsius)") + xlab("Year")

#summerT$yr<- as.integer(summerT$yr) 
ggplot(data=summerT,aes(x=Date, y=X_00010_00003   ))+geom_point()+stat_smooth()+ggtitle(ChoptankInfo$station_nm)+ ylab("Stream temperature (degrees Celsius)") + xlab("Year")

ggplot(data=summerT,aes(x=Date, y=X_00010_00003   ))+geom_point()+stat_smooth()+ggtitle(ChoptankInfo$station_nm)+ ylab("Stream temperature (degrees Celsius)") + xlab("Year")+geom_hline(yintercept = (66-32)*5/9, colour = "red")
```





```{r}
allQ <- readNWISdv(siteNumber,parameterCd,"1994-09-01","2021-09-06")

allQ$yr<-format(allQ$Date, format = "%Y")
allQ$wyr<-0
#allQ[allQ$Date>= as.Date("2003-10-01") & allQ$Date<as.Date("2004-10-01"),]$wyr<-2004
#allQ[allQ$Date>= as.Date("2004-10-01") & allQ$Date<as.Date("2005-10-01"),]$wyr<-2005
allQ[allQ$Date>= as.Date("2005-10-01") & allQ$Date<as.Date("2006-10-01"),]$wyr<-2006
allQ[allQ$Date>= as.Date("2006-10-01") & allQ$Date<as.Date("2007-10-01"),]$wyr<-2007
allQ[allQ$Date>= as.Date("2007-10-01") & allQ$Date<as.Date("2008-10-01"),]$wyr<-2008
allQ[allQ$Date>= as.Date("2008-10-01") & allQ$Date<as.Date("2009-10-01"),]$wyr<-2009
allQ[allQ$Date>= as.Date("2009-10-01") & allQ$Date<as.Date("2010-10-01"),]$wyr<-2010
allQ[allQ$Date>= as.Date("2010-10-01") & allQ$Date<as.Date("2011-10-01"),]$wyr<-2011
allQ[allQ$Date>= as.Date("2011-10-01") & allQ$Date<as.Date("2012-10-01"),]$wyr<-2012
allQ[allQ$Date>= as.Date("2012-10-01") & allQ$Date<as.Date("2013-10-01"),]$wyr<-2013
allQ[allQ$Date>= as.Date("2013-10-01") & allQ$Date<as.Date("2014-10-01"),]$wyr<-2014
allQ[allQ$Date>= as.Date("2014-10-01") & allQ$Date<as.Date("2015-10-01"),]$wyr<-2015
allQ[allQ$Date>= as.Date("2015-10-01") & allQ$Date<as.Date("2016-10-01"),]$wyr<-2016
allQ[allQ$Date>= as.Date("2016-10-01") & allQ$Date<as.Date("2017-10-01"),]$wyr<-2017
allQ[allQ$Date>= as.Date("2017-10-01") & allQ$Date<as.Date("2018-10-01"),]$wyr<-2018
allQ[allQ$Date>= as.Date("2018-10-01") & allQ$Date<as.Date("2019-10-01"),]$wyr<-2019
allQ[allQ$Date>= as.Date("2019-10-01") & allQ$Date<as.Date("2020-10-01"),]$wyr<-2020

summer_2020<-allQ[allQ$Date>= as.Date("2020-06-01") & allQ$Date<as.Date("2020-08-31"),]
summer_2021<-allQ[allQ$Date>= as.Date("2021-06-01") & allQ$Date<as.Date("2021-08-31"),]

allQ

allQ$wyr<-as.factor(allQ$wyr)
ggplot(data=allQ,aes(x=wyr, y=X_00060_00003   ))+geom_boxplot()
allQ$wyr<-as.numeric(as.character(allQ$wyr))
head(allQ)
save(allQ,file = "13092747.Rdata")

```

```{r}
summer_2015<-allQ[allQ$Date>= as.Date("2015-06-01") & allQ$Date<as.Date("2015-08-31"),]
hist(summer_2015$X_00060_00003, xlim=c(0,700), ylim=c(0,50))
summer_2016<-allQ[allQ$Date>= as.Date("2016-06-01") & allQ$Date<as.Date("2016-08-31"),]
hist(summer_2016$X_00060_00003, xlim=c(0,700), ylim=c(0,50))
summer_2017<-allQ[allQ$Date>= as.Date("2017-06-01") & allQ$Date<as.Date("2017-08-31"),]
hist(summer_2017$X_00060_00003, xlim=c(0,700), ylim=c(0,50))
summer_2018<-allQ[allQ$Date>= as.Date("2018-06-01") & allQ$Date<as.Date("2018-08-31"),]
hist(summer_2018$X_00060_00003, xlim=c(0,700), ylim=c(0,50))
summer_2019<-allQ[allQ$Date>= as.Date("2019-06-01") & allQ$Date<as.Date("2019-08-31"),]
hist(summer_2019$X_00060_00003, xlim=c(0,700) , ylim=c(0,50) )
summer_2020<-allQ[allQ$Date>= as.Date("2020-06-01") & allQ$Date<as.Date("2020-08-31"),]
hist(summer_2020$X_00060_00003, xlim=c(0,700) , ylim=c(0,50) )

summer_1617<-rbind(summer_2016,summer_2017)
summer_1517<-rbind(summer_2015,summer_1617)
summer_1518<-rbind(summer_2018,summer_1617)
hist(summer_1518$X_00060_00003, xlim=c(0,700) , ylim=c(0,200) )

summer_2021<-allQ[allQ$Date>= as.Date("2021-06-01") & allQ$Date<as.Date("2021-08-31"),]
hist(summer_2021$X_00060_00003, xlim=c(0,700) , ylim=c(0,50) )
par(new=T)


```


<!-- ```{r} -->
<!-- load("14092750.Rdata") -->
<!-- ``` -->

```{r}
hydrograph(allQ[allQ$wyr %in% c(2010:2014),c(3:4)])
```




<!-- ```{r} -->


<!-- hist(c[c$wy=="2015",]$PRCP,breaks = c(0,5,10,15,25,30) ) -->
<!-- hist(c[c$wy=="2016",]$PRCP ) -->
<!-- hist(c[c$wy=="2017",]$PRCP ) -->
<!-- hist(c[c$wy=="2018",]$PRCP ,breaks = c(0,5,10,15,25,30)) -->
<!-- hist(c[c$wy=="2019",]$PRCP ) -->

<!-- plot(c[c$wy=="2015",]$DATE,c[c$wy=="2015",]$PRCP ) -->
<!-- plot(c[c$wy=="2016",]$DATE,c[c$wy=="2016",]$PRCP) -->
<!-- plot(c[c$wy=="2018",]$DATE,c[c$wy=="2018",]$PRCP) -->
<!-- plot(c[c$wy=="2019",]$DATE,c[c$wy=="2019",]$PRCP) -->

<!-- hist(allQ[allQ$wyr=="2015" ,]$X_00060_00003,breaks = c(0,5000,10000,15000,25000,30000)) -->
<!-- hist(allQ[allQ$wyr=="2016" ,]$X_00060_00003) -->
<!-- hist(allQ[allQ$wyr=="2017" ,]$X_00060_00003) -->
<!-- hist(allQ[allQ$wyr=="2018" ,]$X_00060_00003,breaks = c(0,5000,10000,15000,25000,30000)) -->
<!-- ``` -->


<!-- ```{r} -->

<!-- meanQ<-aggregate(allQ$X_00060_00003 ,list(allQ$wyr ),mean) #cubic feet per second (Mean) -->



<!-- colnames(meanQ)<-c("wyr","Q") -->

<!-- rq<- merge(meanQ,mean_rain,by.x="wyr",by.y="wyr") -->
<!-- rq$rp<-rq$Q *(0.3048)^3*86400* 365/ (271 *1.609*1.609*10^6)/ (rq$mean_rain*12*10/1000)  -->
<!-- # ft^3/s*s/d*d/(mi^2* m/mi *m/mi) -->
<!-- rq -->




<!-- ``` -->


<!-- ```{r} -->
<!-- for (m in c(8:9)) { -->
<!--  print(paste("asc",m,"<-paste(",sep="")) -->
<!--   print(paste("PRISM_ppt_stable_4kmM3_,wyr,0",m,"_asc.asc",",sep=",sep="")) -->

<!--    print(paste("r",m,sep="")) -->

<!-- } -->
<!-- ``` -->



```{r}
df<-data.frame("wyr"=0,"prcp"=0)

for (wyr in c(2006:2019))
{
  setwd(paste("C:/Users/taohuang/Documents/Tao/Data/PRISM/PRISM_ppt_stable_4kmM3_",wyr-1,"_all_asc",sep=""))
  print(wyr)
  asc10<-paste("PRISM_ppt_stable_4kmM3_",wyr-1,"10_asc.asc",sep="")
  r10<-raster(asc10)
    asc11<-paste("PRISM_ppt_stable_4kmM3_",wyr-1,"11_asc.asc",sep="")
  r11<-raster(asc11)
    asc12<-paste("PRISM_ppt_stable_4kmM3_",wyr-1,"12_asc.asc",sep="")
  r12<-raster(asc12)
    setwd(paste("C:/Users/taohuang/Documents/Tao/Data/PRISM/PRISM_ppt_stable_4kmM3_",wyr,"_all_asc",sep=""))
      asc1<-paste("PRISM_ppt_stable_4kmM3_",wyr,"01_asc.asc",sep="")
  r1<-raster(asc1)
        asc2<-paste("PRISM_ppt_stable_4kmM3_",wyr,"02_asc.asc",sep="")
  r2<-raster(asc2)
asc3<-paste("PRISM_ppt_stable_4kmM3_",wyr,"03_asc.asc",sep="")
  r3<-raster(asc3)
asc4<-paste("PRISM_ppt_stable_4kmM3_",wyr,"04_asc.asc",sep="")
              r4<-raster(asc4)
asc5<-paste("PRISM_ppt_stable_4kmM3_",wyr,"05_asc.asc",sep="")
              r5<-raster(asc5)
asc6<-paste("PRISM_ppt_stable_4kmM3_",wyr,"06_asc.asc",sep="")
              r6<-raster(asc6)
asc7<-paste("PRISM_ppt_stable_4kmM3_",wyr,"07_asc.asc",sep="")
              r7<-raster(asc7)
asc8<-paste("PRISM_ppt_stable_4kmM3_",wyr,"08_asc.asc",sep="")
              r8<-raster(asc8)
asc9<-paste("PRISM_ppt_stable_4kmM3_",wyr,"09_asc.asc",sep="")
              r9<-raster(asc9)
             r<-r1+r2+r3+r4+r5+r6+r7+r8+r9+r10+r11+r12 
             class(r)
             
             poly <- readShapePoly("C:/Users/taohuang/Documents/Tao/Data/14400000/layers/globalwatershed.shp")
             ex <- extract(r, poly, fun=mean, na.rm=TRUE, df=TRUE)
             
             df_wyr<-data.frame("wyr"=wyr,"prcp"=ex$layer)
              df<-rbind( df_wyr, df)
}
#save(df,file="C:/Users/taohuang/Documents/Tao/NWCC/NWCC/14092750_rain.Rdata")

```

```{r}
load("14092750_rain.Rdata")
```


```{r}

meanQ<-aggregate(allQ$X_00060_00003 ,list(allQ$wyr ),mean) #cubic feet per second (Mean)

colnames(meanQ)<-c("wyr","Q")

rq<- merge(meanQ, df,by.x="wyr",by.y="wyr")
rq$rp<-rq$Q *(0.3048)^3*86400* 365/ (ChoptankInfo$drain_area_va *1.609*1.609*10^6)/ (rq$prcp /1000) 
# ft^3/s*s/d*d/(mi^2* m/mi *m/mi)
rq

plot(rq$prcp,rq$Q)
plot(rq$prcp,rq$rp)

plot(rq[rq$wyr %in% c(2010:2014),]$prcp,rq[rq$wyr %in% c(2010:2014),]$Q)
plot(rq[rq$wyr %in% c(2010:2014),]$prcp,rq[rq$wyr %in% c(2010:2014),]$rp)

plot(rq[rq$wyr %in% c(2006:2011),]$prcp,rq[rq$wyr %in% c(2006:2011),]$rp)
plot(rq[rq$wyr %in% c(2013:2018),]$prcp,rq[rq$wyr %in% c(2013:2018),]$rp)
```

